export const S = {
  bg: "#0a0e1a",
  card: "#111827",
  border: "#1e2a3a",
  gold: "#f5a623",
  green: "#00b894",
  red: "#FF6B6B",
  yellow: "#f5a623",
  purple: "#6c5ce7",
  blue: "#0984e3",
  textMain: "#e8e8e8",
  textMuted: "#9ca3af",
  textDim: "#6b7280",
  font: "'Nunito', sans-serif",
  fontTitle: "'Bowlby One SC', sans-serif",
};

export const QUOTES = [
  { text: "Les hommes politiques, il y en a, pour briller en société, ils mangeraient du cirage.", author: "Coluche" },
  { text: "La politique, c'est pas compliqué, il suffit d'avoir une bonne conscience, et pour ça il faut avoir une mauvaise mémoire.", author: "Coluche" },
  { text: "C'est pas parce qu'ils sont nombreux à avoir tort qu'ils ont raison.", author: "Coluche" },
  { text: "Un homme politique, c'est un homme qui vous demande de lui donner votre voix. C'est déjà suspect.", author: "Coluche" },
  { text: "La moitié des hommes politiques sont des bons à rien. Les autres sont prêts à tout.", author: "Coluche" },
  { text: "Dieu a dit : « Il faut partager. » Les riches auront la nourriture, les pauvres de l'appétit.", author: "Coluche" },
  { text: "Vivons heureux en attendant la mort.", author: "Pierre Desproges" },
  { text: "On peut rire de tout, mais pas avec n'importe qui.", author: "Pierre Desproges" },
  { text: "L'homme politique est un acrobate : il se maintient en équilibre en disant le contraire de ce qu'il fait.", author: "Pierre Desproges" },
  { text: "En politique, on succède à des imbéciles et on est remplacé par des incapables.", author: "Georges Clemenceau" },
  { text: "La politique, c'est l'art d'empêcher les gens de se mêler de ce qui les regarde.", author: "Paul Valéry" },
  { text: "Un politicien ne pourrait pas exister s'il avait un miroir à la place de la conscience.", author: "Guy Bedos" },
  { text: "Les promesses des hommes politiques n'engagent que ceux qui les écoutent.", author: "Henri Queuille" },
  { text: "Je ne fais pas de politique. C'est comme l'andouillette, ça sent la merde et c'est toujours les mêmes qui en redemandent.", author: "Michel Audiard" },
  { text: "Les cons, ça ose tout. C'est même à ça qu'on les reconnaît.", author: "Michel Audiard" },
  { text: "La démocratie, c'est cinq minutes dans l'isoloir et cinq ans les doigts dans le nez.", author: "Thierry Le Luron" },
  { text: "La France est un pays extrêmement fertile : on y plante des fonctionnaires et il y pousse des impôts.", author: "Georges Clemenceau" },
  { text: "Être de gauche ou de droite, c'est comme être d'accord ou pas d'accord… avec personne.", author: "Raymond Devos" },
  { text: "Heureux les fêlés, car ils laisseront passer la lumière.", author: "Michel Audiard" },
  { text: "Si les Français savaient le rôle que joue l'argent en politique, la porte des prisons ne serait pas assez grande.", author: "Honoré de Balzac" },
  { text: "Il n'y a pas de rapport entre ce que les hommes politiques disent et ce qu'ils pensent.", author: "André Malraux" },
  { text: "La politique, c'est comme le hockey : on finit toujours à la bande.", author: "Pierre Dac" },
  { text: "L'homme politique pense aux prochaines élections, l'homme d'État à la prochaine génération.", author: "Winston Churchill" },
  { text: "Quand on veut gouverner les hommes, il ne faut pas les chasser devant soi, il faut les suivre.", author: "Montesquieu" },
  { text: "Le pouvoir sans abus perd le charme.", author: "Paul Valéry" },
  { text: "Tout le monde savait que c'était impossible. Il est venu un imbécile qui ne le savait pas et qui l'a fait.", author: "Marcel Pagnol" },
  { text: "La politique est le moyen pour des hommes sans principes de diriger des hommes sans mémoire.", author: "Voltaire" },
  { text: "Quand les types de 130 kilos disent certaines choses, ceux de 60 kilos les écoutent.", author: "Michel Audiard" },
  { text: "Je suis leur chef, il fallait bien que je les suive.", author: "Alexandre Ledru-Rollin" },
  { text: "Un bon politicien est celui qui est capable de prédire l'avenir et qui, par la suite, est capable d'expliquer pourquoi les choses ne se sont pas passées comme il l'avait prédit.", author: "Winston Churchill" },
  { text: "Le secret de la réussite en politique ? Faire croire que l'on est bête. C'est assez facile.", author: "Pierre Desproges" },
  { text: "La politique, c'est l'art de se servir des gens.", author: "Henry de Montherlant" },
  { text: "Le mot le plus court en politique est le mot 'promesse'. Il dure le temps d'un discours.", author: "Léo Campion" },
  { text: "En politique, ce n'est pas les idées qui comptent, mais les circonstances.", author: "Charles de Gaulle" },
  { text: "Un politicien, c'est un monsieur qui vous demande de l'argent pour la campagne et qui après, dépense le vôtre.", author: "Coluche" },
  { text: "En politique, il faut donner ce qu'on n'a pas, promettre ce qu'on ne peut pas et pardonner ce qu'on ne veut pas.", author: "Jean-Charles" },
  { text: "On ne ment jamais autant qu'avant les élections, pendant la guerre et après la chasse.", author: "Otto von Bismarck" },
  { text: "Les promesses n'engagent que ceux qui y croient.", author: "Jacques Chirac" },
  { text: "Si voter changeait vraiment quelque chose, ça ferait longtemps que ce serait interdit.", author: "Coluche" },
  { text: "La politique, c'est pas un métier, c'est une situation.", author: "Coluche" },
  { text: "Je n'ai qu'une seule crainte, c'est que l'avenir ne me donne raison.", author: "Charles de Gaulle" },
  { text: "La république, c'est le gouvernement provisoire qui dure.", author: "Victor Hugo" },
  { text: "En France, tout le monde est socialiste, sauf ceux qui le disent.", author: "Philippe Bouvard" },
  { text: "Un politicien se doit d'être capable de prédire ce qui va arriver demain, la semaine prochaine, le mois prochain et l'année prochaine. Et d'être capable, par la suite, d'expliquer pourquoi rien de tout cela n'est arrivé.", author: "Winston Churchill" },
  { text: "Un député, ça ne sert à rien, mais ça peut servir à tout.", author: "Jacques Chirac" },
  { text: "Gouverner, c'est pleuvoir.", author: "Pierre Dac" },
  { text: "Si vous trouvez que l'éducation coûte cher, essayez l'ignorance.", author: "Abraham Lincoln" },
  { text: "Le monde est dangereux à vivre ! Non pas tant à cause de ceux qui font le mal, mais à cause de ceux qui regardent et laissent faire.", author: "Albert Einstein" },
  { text: "La dictature c'est 'Ferme ta gueule !', la démocratie c'est 'Cause toujours !'.", author: "Woody Allen" },
  { text: "Celui qui ne gueule pas la vérité quand il connaît la vérité se fait le complice des menteurs et des faussaires.", author: "Charles Péguy" },
  { text: "Les hommes politiques et les couches-culottes doivent être changés souvent. Et pour les mêmes raisons.", author: "George Bernard Shaw" },
  { text: "Il vaut mieux avoir une fausse joie qu'une vraie tristesse.", author: "Pierre Desproges" },
  { text: "Le problème avec les citations sur Internet, c'est qu'on ne peut jamais être sûr de leur authenticité.", author: "Abraham Lincoln" },
  { text: "En politique, on n'a pas de convictions, on n'a que des intérêts.", author: "Talleyrand" },
  { text: "La politique est le seul métier qui se passe de diplôme.", author: "Coluche" },
  { text: "Les Français sont des veaux.", author: "Charles de Gaulle" },
  { text: "Je ne suis ni pour ni contre, bien au contraire.", author: "Coluche" },
  { text: "En politique, une absurdité n'est pas un obstacle.", author: "Napoléon Bonaparte" },
  { text: "Le patriotisme, c'est aimer son pays. Le nationalisme, c'est détester celui des autres.", author: "Charles de Gaulle" },
  { text: "Voter, c'est abdiquer.", author: "Élisée Reclus" },
  { text: "Un peuple prêt à sacrifier un peu de liberté pour un peu de sécurité ne mérite ni l'une ni l'autre, et finit par perdre les deux.", author: "Benjamin Franklin" },
  { text: "La meilleure forteresse des tyrans, c'est l'inertie des peuples.", author: "Machiavel" },
  { text: "Quand on met la charrue avant les bœufs, on finit par se faire labourer.", author: "Pierre Dac" },
  { text: "Le pouvoir use surtout ceux qui ne l'ont pas.", author: "Giulio Andreotti" },
  { text: "Un ministre, ça ferme sa gueule. Si ça veut l'ouvrir, ça démissionne.", author: "Jean-Pierre Chevènement" },
  { text: "Il est plus facile de faire la guerre que la paix.", author: "Georges Clemenceau" },
  { text: "La politique est l'art de chercher les problèmes, de les trouver, de les mal diagnostiquer et d'appliquer les mauvais remèdes.", author: "Groucho Marx" },
  { text: "Le pouvoir est comme un violon. On le prend de la main gauche et on joue de la droite.", author: "Itzhak Stern" },
  { text: "En France, on a pas de pétrole, mais on a des idées... et surtout des impôts.", author: "Coluche" },
  { text: "Si les hommes politiques disaient la vérité, ça se saurait.", author: "Guy Bedos" },
  { text: "La France est le seul pays où quand on change le gouvernement, on ne change pas la politique.", author: "Jean-François Revel" },
  { text: "Le problème avec la France, c'est qu'elle est pleine de Français.", author: "Clémenceau (attribué)" },
  { text: "Quand on parle pognon, à partir d'un certain chiffre, tout le monde écoute.", author: "Michel Audiard" },
  { text: "Un bon discours politique est celui qui ferme toutes les portes et laisse toutes les fenêtres ouvertes.", author: "Pierre Dac" },
  { text: "La différence entre un politicien et un pickpocket, c'est que le pickpocket ne vous demande pas de voter pour lui ensuite.", author: "Coluche" },
  { text: "Quand je me regarde, je me désole. Quand je me compare, je me console.", author: "Talleyrand" },
  { text: "La politique, c'est une certaine façon d'agiter le peuple avant de s'en servir.", author: "Talleyrand" },
  { text: "Il n'y a pas de honte à préférer le bonheur.", author: "Albert Camus" },
  { text: "Le courage, c'est de comprendre sa propre vie. Le courage, c'est d'aimer la vie et de regarder la mort d'un regard tranquille.", author: "Jean Jaurès" },
  { text: "Quand les riches se font la guerre, ce sont les pauvres qui meurent.", author: "Jean-Paul Sartre" },
  { text: "On ne résout pas un problème avec les modes de pensée qui l'ont engendré.", author: "Albert Einstein" },
  { text: "La liberté des uns s'arrête là où commence celle des autres.", author: "John Stuart Mill" },
  { text: "Plus ça change, plus c'est la même chose.", author: "Alphonse Karr" },
];
